version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      # - DATABASE_URL=mongodb://mongo:27017/tablecheck_development
      - REDIS_URL=redis://redis:6379
      - SIDEKIQ_URL=redis://redis:6379
    volumes:
      - .:/rails

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data

  sidekiq:
    build: .
    command: ["bundle", "exec", "sidekiq"]
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

volumes:
  mongo-data:
  redis-data:
