version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    depends_on:
      - mongo
      - redis
    environment:
      - DATABASE_URL=mongodb://mongo:27017/my_app
      - REDIS_URL=redis://redis:6379
      - SIDEKIQ_URL=redis://redis:6379

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data

  sidekiq:
    build: .
    command: sidekiq
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

volumes:
  mongo-data:
  redis-data:
